
submit_ticket:
    path:     /tickets/submit
    defaults: { _controller: AppBundle:Sales:submitTicket }

ticket_submission_successful:
    path:     /tickets/submit/success
    defaults: { _controller: AppBundle:Sales:ticketSubmissionSuccessful }

signup:
    path:     /signup
    defaults: { _controller: AppBundle:Login:signUp}

login:
    path:     /login
    defaults: { _controller: AppBundle:Login:login}